sudo: false
dist: trusty
language: java
jdk:
  - openjdk8
  - openjdk11
before_install:
  - rm ~/.m2/settings.xml || true
  - ulimit -c unlimited -S
  - mvn -N io.takari:maven:wrapper
after_success:
  - bash .travis_after_success.sh
cache:
  directories:
    - $HOME/.m2
env:
  global:
    - secure: "DfDfaPKIE/pvu4LH2dbsk+bXq4gFtFN1/p6sF36r46w96piIM8NuizPISzUFVStyG1V9KryCA/OMywxLiky43EnotCOPFQdz4SvcowEM8kbxotauAKu6kkd8Gh3MHD4NHRP3BGNq74JM+Bgq1IipHUpCGfz9COA3JMvAtWDnjzk="
    - secure: "u/rc6nrg2L7qo/rvCezRxTHLKwS/R7x6Pjv4ZDYJagdBzGyGvDQ/4lM8eMqQlV6iSXvhlRGPadRb85Us62InYYMElDkOyTmWEHTUxUYMpqQQhVsuctzG+qtGMmMx9BFOECIllVf/xUBRWYes+a14TBu6NNVy55P8Zsx9N5zVDS8="